# Generated by Django 4.2.6 on 2023-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carton_pieces', models.IntegerField()),
                ('carton_num', models.IntegerField()),
                ('carton_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peice_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peice_quentity', models.IntegerField()),
                ('barcode', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
