# Generated by Django 4.2.6 on 2023-11-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_date_intiated_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='piece_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
