# Generated by Django 4.2.6 on 2023-11-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cashier_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_shift', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
