# Generated by Django 4.2.6 on 2023-11-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderreceiptproduct',
            name='new_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
