# Generated by Django 4.2.6 on 2023-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_product', '0002_traderreceiptproduct_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderreceiptproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
