# Generated by Django 4.2.6 on 2023-11-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
        ('receipt_product', '0003_traderreceiptproduct_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderreceiptproduct',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipt.traderreceipt'),
        ),
    ]
