# Generated by Django 4.2.6 on 2023-11-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_product', '0004_alter_traderreceiptproduct_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderreceiptproduct',
            name='new_field',
        ),
    ]
