# Generated by Django 4.2.6 on 2023-10-17 18:01

from django.db import migrations
from django.db import migrations
from django.contrib.auth import get_user_model
from user.models import CustomUser
from django.contrib.auth.models import Permission

def create_superuser(apps, schema_editor):
    User = get_user_model()
    superuser = User.objects.create_superuser('admin', '123')
    superuser.set_password('123')
    superuser.save()

def assign_permissions(apps, schema_editor):
    User = get_user_model()
    user = User.objects.get(username='admin')
    permissions = Permission.objects.all()  
    user.user_permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(assign_permissions),
    ]

   